version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ats-db
    environment:
      POSTGRES_DB: atsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: ats-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:password@db:5432/atsdb?schema=public
      - JWT_SECRET=9a67471b79e162125a1e2f8d227c8a4a5840d2d3e1cfcf0d491c303f8f1cfa36573c73bbec24259b
      - JWT_EXPIRATION_MS=86400000
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: ats-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
